namespace Core.Resources.Enums
{
    public enum ProjectModelType : short
    {
        Blog = 1,
        BlogCategory = 2,
        StudentOperationClaim = 3,
        Course = 4,
        CourseComment = 5,
        CourseService = 6,
        Language = 7,
        Localization = 8,
        Media = 9,
        Message = 10,
        OperationClaim = 11,
        Phrase = 12,
        Exam = 13,
        ProfessionCourseCategory = 14,
        SharingType = 15,
        SharingTypeMedia = 16,
        Slider = 17,
        SocialMedia = 18,
        Tag = 19,
        TagBlog = 20,
        Teacher = 21,
        TeacherCourse = 22,
        TeacherSocialMedia = 23,
        User = 24,
        StudentStudyingGroup = 25,
        UserOperationClaim = 26,
        UserSocialMedia = 27,
        Student = 28,
        TeacherOperationClaim = 29,
        ExamQuestion = 30,
        StudyingGroup = 31,
        AnswerVariation = 32,
        Question = 33,
        QuestionResultExam = 34,
        QuestionVariation = 35,
        ResultExam = 36,
        Log = 37
    }
}
